/**
 * PIXEL ART, écrit à la main. Chaque sprite est une grille de 16×16 caractères ;
 * `render/textures.ts` la peint case par case, sans jamais interpoler la source.
 *
 * Les lettres sont les MÊMES d'un sprite à l'autre, seule la palette change : on
 * relit un personnage comme un calque, et une retouche de teinte ne demande
 * jamais de redessiner la forme.
 *
 *   .  transparent      o  contour        w  blanc cassé / éclat
 *   k  peau claire      K  peau ombrée    e  œil
 *   h  poil / cheveux   H  poil ombré
 *   c  étoffe           C  étoffe ombrée
 *   a  métal / bois     A  accent ombré   y  or vif
 *   g  végétal          r  chaud (nez, écharpe)      b  froid (rune, fiole)
 *
 * PARTI PRIS ASSUMÉ — RIEN QUI FASSE PEUR. Le bestiaire garde EXACTEMENT les
 * rôles et les chiffres du design, mais ses silhouettes sont rondes, ses yeux
 * grands et ses couleurs chaudes : un rat joufflu, un tas d'os débonnaire, une
 * idole qui ronfle pour de vrai. La menace se lit aux CHIFFRES et à la position
 * sur les lignes, jamais à une image inquiétante — et comme les chiffres sont
 * déterministes, on ne perd aucune information en la retirant de l'image.
 * Même parti pris pour les tells de porte : une lame plutôt qu'un crâne.
 */

/** Côté d'une grille, en pixels d'art. */
export const SPRITE_SIZE = 16;

/** Table de teintes d'un sprite : lettre → couleur. Le `.` n'est jamais peint. */
export type Ink = Readonly<Record<string, number>>;

export interface SpriteDef {
  grid: readonly string[];
  ink: Ink;
}

/** Contour commun : un brun-prune, jamais un noir pur — la charte est chaude. */
const O = 0x2a1420;
/** Encre partagée : contour, peau, œil, éclat crème. */
const BASE = { o: O, k: 0xffd2a8, K: 0xd99b73, e: 0x3d2130, w: 0xfff3dc };

export const SPRITES: Readonly<Record<string, SpriteDef>> = {
  /** Vagabond — capuche ambrée, écharpe corail, bâton de marche. */
  wanderer: {
    grid: [
      '......oooo......',
      '....oohhhhoo....',
      '...ohhhhhhhho...',
      '...ohkkkkkkho..o',
      '...okkekkekko.oa',
      '...okkkkkkkko.oa',
      '....okKKKKko..oa',
      '....orrrrrro..oa',
      '...occcccccco.oa',
      '..occcwwwwccco.a',
      '..occcwwwwcccoaa',
      '..occcccccccco.o',
      '...oCCCCCCCCo...',
      '...oCCoooCCo....',
      '...okko.okko....',
      '...oooo.oooo....',
    ],
    ink: { ...BASE, h: 0xe8a45c, c: 0xc9743f, C: 0x9a5028, r: 0xff8f6b, a: 0xc08a50 },
  },
  /** Gardien — heaume à visière et grand écu rond. Sa mort est un événement. */
  guardian: {
    grid: [
      '.....oooooo.....',
      '....oaaaaaao....',
      '...oaaaaaaaao...',
      '...oakkkkkkao...',
      '...oaekkkkeao...',
      '...oakkkkkkao...',
      '....oaaaaaao....',
      '..ooocccccooo...',
      '.oaaaocccco.....',
      'oaayaaocccco....',
      'oaayyaocccco....',
      'oaayaaoccccco...',
      '.oaaaaoCCCCo....',
      '..oooooCCCCo....',
      '.....oCCoCCo....',
      '.....oooooo.....',
    ],
    ink: { ...BASE, a: 0xddab63, y: 0xffd24a, c: 0xd2694a, C: 0x9b4130 },
  },
  /** Bourreau — bandana chaud et grande hache. Élan récompense l'ouverture. */
  headsman: {
    grid: [
      '..........oooo..',
      '....oooo.oaaaao.',
      '...orrrroaaaaaao',
      '...okkkkkoaaaaao',
      '...okekkeo.oaao.',
      '...okkkkko..oo..',
      '....okKKko..oo..',
      '...occcccco.oAo.',
      '..occwwwcccooAo.',
      '..occwwwccccoAo.',
      '..occcccccco.o..',
      '...oCCCCCCo.....',
      '...oCCCCCCo.....',
      '...oCCoCCo......',
      '...okk.okko.....',
      '...ooo.oooo.....',
    ],
    ink: { ...BASE, r: 0xff7a5c, c: 0xd08f52, C: 0x8f5730, a: 0xf0cc84, A: 0xa8652f },
  },
  /** Archère — natte auburn, arc long. La réponse aux perceurs et aux totems. */
  archer: {
    grid: [
      '.....oooo...o...',
      '....ohhhho.oao..',
      '...ohhhhhho.oao.',
      '...ohkkkkho.o.ao',
      '...okekkeko.o.ao',
      '...okkkkkko.o.ao',
      '....okKKko..o.ao',
      '...occccccco.ao.',
      '..occcwwwcco.ao.',
      '..occcwwwccco.o.',
      '..occcccccco....',
      '...oCCCCCCo.....',
      '...oCCCCCCo.....',
      '...oCCoCCo......',
      '...okk.okko.....',
      '...ooo.oooo.....',
    ],
    ink: { ...BASE, h: 0xc4643c, c: 0xd9a24c, C: 0x8f6428, a: 0xb8763c },
  },
  /** Herboriste — tablier, feuille dans les cheveux, décoction à la main. */
  herbalist: {
    grid: [
      '......oo.gg.....',
      '....oooohgho....',
      '...ohhhhhhhho...',
      '...ohkkkkkkho...',
      '...okekkkeko....',
      '...okkkkkkko....',
      '....okKKKko.....',
      '...occcccco.....',
      '..occwwwwcco....',
      '..occwwwwccooo..',
      '..occcccccogbgo.',
      '...occcccco.ggo.',
      '...oCCCCCCo.oo..',
      '...oCCoCCo......',
      '...okk.okko.....',
      '...ooo.oooo.....',
    ],
    ink: { ...BASE, h: 0x8a5a3c, c: 0xe0b071, C: 0xa87642, g: 0x8fe07a, b: 0x5fd3c4 },
  },
  /** Runiste — robe à capuche, bâton à rune. Extrêmement fragile. */
  runist: {
    grid: [
      '....oooo....oo..',
      '...ocCCco..obbo.',
      '..ocCCCCco.obbo.',
      '..ocCkkkCco.oo..',
      '..ocekkkeco.oa..',
      '..occkkkcco.oa..',
      '...occCCco..oa..',
      '..occCCCCco.oa..',
      '.occCbbCCcooa...',
      '.occCbbCCco.a...',
      '.occCCCCCco.....',
      '..oCCCCCCo......',
      '..oCCCCCCo......',
      '..oCCoCCo.......',
      '..okk.okko......',
      '..ooo.oooo......',
    ],
    ink: { ...BASE, c: 0xe08a5c, C: 0xa85a3c, b: 0x7fe0d8, a: 0xb8763c },
  },
  /** Sœur d'armes — épée et écu, débloquée par la méta. Ouverture de front. */
  sister: {
    grid: [
      '.....oooo...oo..',
      '....ohhhho.oaao.',
      '...ohhhhhho.oao.',
      '...ohkkkkho.oao.',
      '...okekkeko.oao.',
      '...okkkkkko.oao.',
      '....okKKko..oao.',
      '.ooocccccoo.oao.',
      'oaaocccccoo.oao.',
      'oayaocccco.ooaoo',
      'oaaaocccco..oao.',
      '.oooCCCCCo...o..',
      '...oCCCCCo......',
      '...oCCoCCo......',
      '...okk.okko.....',
      '...ooo.oooo.....',
    ],
    ink: { ...BASE, h: 0xf0c060, a: 0xe8cfa0, y: 0xffd24a, c: 0xe0705e, C: 0xa84a42 },
  },
  /** Statue éveillée — un mur consommable, taillé dans un grès chaud. */
  statue: {
    grid: [
      '....oooooooo....',
      '...oaaaaaaaao...',
      '...oaAAAAAAao...',
      '...oabbaabbao...',
      '...oaaaaaaaao...',
      '...oaAaaaaAao...',
      '....oaaaaao.....',
      '..ooaaaaaaaoo...',
      '.oaaaAAAAaaao...',
      '.oaaaAAAAaaao...',
      '.oaaaaaaaaaao...',
      '..oaaaaaaaao....',
      '...oAAAAAAo.....',
      '...oAAoAAo......',
      '...oaa.oaao.....',
      '...ooo.oooo.....',
    ],
    ink: { ...BASE, a: 0xd8a878, A: 0xa97c55, b: 0xffd24a },
  },
  /** Spectre — un petit fantôme rond et joufflu. Deux tours, puis plus rien. */
  wraith: {
    grid: [
      '.....oooooo.....',
      '...ooWWWWWWoo...',
      '..oWWWWWWWWWWo..',
      '..oWWWWWWWWWWo..',
      '..oWWeeWWeeWWo..',
      '..oWWeeWWeeWWo..',
      '..oWWWWWWWWWWo..',
      '..oWWWWrrWWWWo..',
      '..oWWWWWWWWWWo..',
      '..oWWWWWWWWWWo..',
      '..oWWWWWWWWWWo..',
      '..oWWWWWWWWWWo..',
      '..oWWWWWWWWWWo..',
      '..oWoWWoWWoWWo..',
      '..ooo.oo.oo.oo..',
      '................',
    ],
    ink: { ...BASE, W: 0xfff3dc, e: 0x5a3550, r: 0xff9e8a },
  },
  /** Rat-goule — le remplisseur, joufflu et pressé. Apparaît par 2 ou 3. */
  rat: {
    grid: [
      '................',
      '..oo........oo..',
      '.ohho......ohho.',
      '.ohhho....ohhho.',
      '..ohhoooooohho..',
      '..ohhhhhhhhhho..',
      '.ohhhhhhhhhhhho.',
      '.ohheohhhhoehho.',
      '.ohhhhhhhhhhhho.',
      '.ohhhhhkkkhhhho.',
      '..ohhhhkrkhhho..',
      '..ohhhhkkkhhho..',
      '..ohhhhhhhhho...',
      '...ohhhhhhho..oo',
      '...okkoookko.oKo',
      '...oo....oo..oo.',
    ],
    ink: { ...BASE, h: 0xc98a6b, r: 0xff8fa0 },
  },
  /** Brute d'ossements — un tas d'os débonnaire, lent et lourd. Armure 2. */
  brute: {
    grid: [
      '................',
      '....oooooooo....',
      '...owwwwwwwwo...',
      '..owwwwwwwwwwo..',
      '..owweewweewwo..',
      '..owwwwwwwwwwo..',
      '..owwwoooowwwo..',
      '...owwwwwwwwo...',
      '.oooowwwwwwoooo.',
      'owwwowwwwwwowwwo',
      'owwwowwwwwwowwwo',
      '.ooowwwwwwwwooo.',
      '...owwwwwwwwo...',
      '...owwoooowwo...',
      '...oww.o.owwo...',
      '...ooo...oooo...',
    ],
    ink: { ...BASE, w: 0xf5e0be, e: 0x5a3550 },
  },
  /** Rôdeur — capuche et fronde, deux yeux de luciole. LE perceur du bestiaire. */
  stalker: {
    grid: [
      '.....oooo.......',
      '...oocccccoo....',
      '..occccccccco...',
      '..occKKKKKcco...',
      '..occKeeeKcco.oo',
      '..occKKKKKcco.oa',
      '...occcccccoo.oa',
      '..occcCCCCcco.oa',
      '.occcCCCCCCcooa.',
      '.occcCCCCCCco.a.',
      '.occcCCCCCCco...',
      '..occCCCCCCo....',
      '..oCCCCCCCCo....',
      '..oCCCoooCCo....',
      '..okko...okko...',
      '..oooo...oooo...',
    ],
    ink: { ...BASE, c: 0xe8a05c, C: 0xb06a38, K: 0x6a4030, e: 0xffd24a, a: 0xc08a50 },
  },
  /** Chien de meute — museau ouvert, langue dehors. Il agit avant presque tout. */
  hound: {
    grid: [
      '................',
      '..oo.......ooo..',
      '.ohho.....ohhho.',
      '.ohhho...ohhhho.',
      '..ohhooooohhho..',
      '..ohhhhhhhhhho..',
      '.ohhhhhhhhhhhho.',
      '.ohheohhhhoehho.',
      '.ohhhhhhhhhhhho.',
      '..ohhhhkkkhhho..',
      '..ohhhhkrkhhho..',
      '...ohhhwwwhhho..',
      '..ohhhhhhhhhho..',
      '.ohhhoooooohhho.',
      '.okko......okko.',
      '.oooo......oooo.',
    ],
    ink: { ...BASE, h: 0xe0a05a, r: 0xff8fa0 },
  },
  /** Idole ronflante — un totem endormi, bulles de ronflement comprises. */
  idol: {
    grid: [
      '...........oooo.',
      '....oooo...oWWWo',
      '...oaaaao..oooo.',
      '..oaaaaaao.oWo..',
      '..oaAAAAao.ooo..',
      '..oaeeaeeao.....',
      '..oaaaaaaao.....',
      '..oaaggaaao.....',
      '..oaaaaaaao.....',
      '.oaaaaaaaaao....',
      '.oaAAAAAAAao....',
      '.oaaaaaaaaao....',
      '.oaaAAAAAaao....',
      '.oaaaaaaaaao....',
      '.ooooooooooo....',
      '................',
    ],
    ink: { ...BASE, a: 0xe8b87a, A: 0xb07e4a, e: 0x6a4030, g: 0x8fe07a, W: 0xfff3dc },
  },
  /** Le Geôlier — gros gardien bougon, trousseau de clés au ceinturon. */
  jailer: {
    grid: [
      '................',
      '....oooooooo....',
      '...occccccco....',
      '..occccccccco...',
      '..occkkkkkcco...',
      '..ocKeKKKeKcco..',
      '..occkkkkkkcco..',
      '..occckkkccco...',
      '.oocccccccccoo..',
      'oaacccwwwcccaao.',
      'oaacccwwwcccaao.',
      '.oocccccccccoo.o',
      '..occcccccccoyo.',
      '..oCCCCCCCCCoyo.',
      '..oCCo...oCCooo.',
      '..ooo.....ooo...',
    ],
    ink: { ...BASE, c: 0xe09a55, C: 0xa8642f, a: 0xd2694a, y: 0xffd24a },
  },
  /** Écu bosselé — −2 dégâts subis au contact. */
  itemShield: {
    grid: [
      '................',
      '...oooooooooo...',
      '..oaaaaaaaaaao..',
      '..oaaayyyyaaao..',
      '..oaayyyyyyaao..',
      '..oaayyaayyaao..',
      '..oaaayyyyaaao..',
      '..oaaaaaaaaaao..',
      '..oaaaaaaaaaao..',
      '...oaaaaaaaao...',
      '...oaaaaaaaao...',
      '....oaaaaaao....',
      '.....oaaaao.....',
      '......oaao......',
      '.......oo.......',
      '................',
    ],
    ink: { ...BASE, a: 0xddab63, y: 0xffd24a },
  },
  /** Lame ébréchée — +3 ATQ. L'ébréchure est le trou 'n' dans le fil. */
  itemBlade: {
    grid: [
      '.............oo.',
      '............oaao',
      '...........oaaao',
      '..........oaaao.',
      '.........oaaao..',
      '........oaaao...',
      '.......oaano....',
      '......oaaao.....',
      '.....oaaao......',
      '....oaaao.......',
      '...oyyyo........',
      '..oyyyyo........',
      '..oAAo..........',
      '.oAAo...........',
      '.oAo............',
      '.oo.............',
    ],
    ink: { ...BASE, a: 0xe8cfa0, n: 0xb08a5a, y: 0xffd24a, A: 0xa8652f },
  },
  /** Bottes lestées — la première permutation d'un combat est offerte. */
  itemBoots: {
    grid: [
      '................',
      '..oooo....oooo..',
      '..occo....occo..',
      '..occo....occo..',
      '..occo....occo..',
      '..occo....occo..',
      '..occo....occo..',
      '..occoo...occoo.',
      '..occcoo..occcoo',
      '..occccoooccccoo',
      '..occccccoccccco',
      '..oCCCCCCoCCCCCo',
      '..oyyyyyyoyyyyyo',
      '..oooooooooooooo',
      '................',
      '................',
    ],
    ink: { ...BASE, c: 0xc9743f, C: 0x8a4a26, y: 0xddab63 },
  },
  /** Amulette de sève — +6 PV max, et 3 PV rendus en fin de combat. */
  itemAmulet: {
    grid: [
      '................',
      '...oo......oo...',
      '..oaao....oaao..',
      '..oaaoo..ooaao..',
      '...oaaoooaao....',
      '....oaaaaao.....',
      '.....ogggo......',
      '....oggggggo....',
      '...oggggggggo...',
      '...oggwwwgggo...',
      '...oggwwwgggo...',
      '...oggggggggo...',
      '....oggggggo....',
      '.....ogggo......',
      '......ooo.......',
      '................',
    ],
    ink: { ...BASE, a: 0xddab63, g: 0x8fe07a, w: 0xfff3dc },
  },
  /** Carquois lourd — l'unité ignore toute règle de ciblage. */
  itemQuiver: {
    grid: [
      '.....oo.oo.oo...',
      '....owwowwoowo..',
      '....owwowwoowo..',
      '.....oaooaooao..',
      '.....oaooaooao..',
      '...oooaooaooaoo.',
      '..occaccaccaacco',
      '..occcccccccccco',
      '..occCCCCCCCCcco',
      '..occcccccccccco',
      '..occCCCCCCCCcco',
      '..occcccccccccco',
      '..occCCCCCCCCcco',
      '..occcccccccccco',
      '...oooooooooooo.',
      '................',
    ],
    ink: { ...BASE, w: 0xfff3dc, a: 0xb8763c, c: 0xd08f52, C: 0x8f5730 },
  },
  /** Fanion usé — +2 INIT à toute l'escouade. */
  itemBanner: {
    grid: [
      '....oo..........',
      '...oaao.........',
      '...oaaooooooo...',
      '...oaacccccco...',
      '...oaacwwwcco...',
      '...oaacwwwcCo...',
      '...oaaccccCCo...',
      '...oaacccCCo....',
      '...oaaccCCo.....',
      '...oaacCCo......',
      '...oaaoo........',
      '...oaao.........',
      '...oaao.........',
      '...oaao.........',
      '..ooaaoo........',
      '..oooooo........',
    ],
    ink: { ...BASE, a: 0xb8763c, c: 0xe0705e, C: 0xa84a42, w: 0xfff3dc },
  },
  /** Combat standard — UNE lame. Le design dit « crâne » ; on préfère une arme, le tell reste unique et rien ne fait peur. */
  doorFight: {
    grid: [
      '................',
      '.........oo.....',
      '........oaao....',
      '.......oaaao....',
      '......oaaao.....',
      '.....oaaao......',
      '....oaaao.......',
      '...oaaao........',
      '..oaaao.........',
      '..oyyo..........',
      '.oyyyyo.........',
      '.oAAAo..........',
      'oAAAo...........',
      'oAAo............',
      '.oo.............',
      '................',
    ],
    ink: { ...BASE, a: 0xe8cfa0, y: 0xffd24a, A: 0xa8652f },
  },
  /** Combat dangereux — DEUX lames croisées : le tell double, comme les crânes. */
  doorFightHard: {
    grid: [
      '.....oo...oo....',
      '....oaao.oaao...',
      '....oaaaoaaao...',
      '.....oaaaaao....',
      '......oaaao.....',
      '.....oaaaaao....',
      '....oaaaoaaao...',
      '...oaaao.oaaao..',
      '..oaaao...oaaao.',
      '..oyyo.....oyyo.',
      '.oyyyo.....oyyyo',
      '.oAAo.......oAAo',
      'oAAo.........oAo',
      'oAo...........oo',
      '.o..............',
      '................',
    ],
    ink: { ...BASE, a: 0xe8cfa0, y: 0xffd24a, A: 0xa8652f },
  },
  /** Recrue — une silhouette, exactement le tell du design. */
  doorRecruit: {
    grid: [
      '................',
      '.....oooooo.....',
      '....okkkkkko....',
      '...okkkkkkkko...',
      '...okkekkekko...',
      '...okkkkkkkko...',
      '....okkkkkko....',
      '.....okkkko.....',
      '...oocccccoo....',
      '..occccccccco...',
      '..occcccccccco..',
      '..occcccccccco..',
      '..occcccccccco..',
      '..occcccccccco..',
      '..occcccccccco..',
      '..ooooooooooo...',
    ],
    ink: { ...BASE, c: 0xe8a45c },
  },
  /** Trésor — un coffre : objet ou invocation. */
  doorTreasure: {
    grid: [
      '................',
      '...oooooooooo...',
      '..occcccccccco..',
      '..occwwwwwwcco..',
      '..occcccccccco..',
      '.oooooooooooooo.',
      '.oaaaaaaaaaaaao.',
      '.oaaaaayyaaaaao.',
      '.oCCCCCyyCCCCCo.',
      '.oCCCCCyyCCCCCo.',
      '.oCCCCCCCCCCCCo.',
      '.oCCCCCCCCCCCCo.',
      '.oCCCCCCCCCCCCo.',
      '.oaaaaaaaaaaaao.',
      '.oooooooooooooo.',
      '................',
    ],
    ink: { ...BASE, c: 0xc9743f, C: 0x8a4a26, a: 0xddab63, y: 0xffd24a, w: 0xe0b071 },
  },
  /** Marchand — une bourse, ficelle comprise. */
  doorShop: {
    grid: [
      '................',
      '......oooo......',
      '.....oaaaao.....',
      '....oaoooao.....',
      '....oao..oao....',
      '...ooo....ooo...',
      '..occccccccco...',
      '..occcccccccco..',
      '.occcyyyyyccco..',
      '.occcyoooycccco.',
      '.occcyoooycccco.',
      '.occcyyyyycccco.',
      '.occcccccccccco.',
      '.occcccccccccco.',
      '..oooooooooooo..',
      '................',
    ],
    ink: { ...BASE, c: 0xc9743f, a: 0xb8763c, y: 0xffd24a },
  },
  /** Porte voilée — le pari : contenu inconnu, récompense majorée de 50 %. */
  doorVeiled: {
    grid: [
      '................',
      '.....oooooo.....',
      '....oyyyyyyo....',
      '...oyyoooyyyo...',
      '...oyyo..oyyo...',
      '...oooo..oyyo...',
      '........oyyyo...',
      '.......oyyyo....',
      '......oyyyo.....',
      '......oyyo......',
      '......oyyo......',
      '......oooo......',
      '................',
      '......oooo......',
      '......oyyo......',
      '......oooo......',
    ],
    ink: { ...BASE, y: 0xffd24a },
  },
};
